export const countriesSelect = [
    { value: 'fr', text: 'France' },
    { value: 'de', text: 'Allemagne' },
    { value: 'dz', text: 'Algérie' },
    { value: 'mr', text: 'Maroc' },
    { value: 'tn', text: 'Tunisie' },
    { value: 'dz', text: 'Algérie' },
    { value: 'es', text: 'Espagne' },
    { value: 'it', text: 'Italie' },
    { value: 'gb', text: 'Royaume-Uni' },
    { value: 'us', text: 'États-Unis' },
    { value: 'ca', text: 'Canada' },
    { value: 'jp', text: 'Japon' },
    { value: 'cn', text: 'Chine' },
    { value: 'in', text: 'Inde' },
    { value: 'br', text: 'Brésil' },
    { value: 'mx', text: 'Mexique' },
    { value: 'ru', text: 'Russie' },
    { value: 'za', text: 'Afrique du Sud' },
    { value: 'au', text: 'Australie' },
    { value: 'ar', text: 'Argentine' },
    { value: 'be', text: 'Belgique' },
    { value: 'ch', text: 'Suisse' },
    { value: 'cl', text: 'Chili' },
    { value: 'co', text: 'Colombie' },
    { value: 'cz', text: 'République Tchèque' },
    { value: 'dk', text: 'Danemark' },
    { value: 'eg', text: 'Égypte' },
    { value: 'fi', text: 'Finlande' },
    { value: 'gr', text: 'Grèce' },
    { value: 'hu', text: 'Hongrie' },
    { value: 'id', text: 'Indonésie' },
    { value: 'ie', text: 'Irlande' },
    { value: 'il', text: 'Israël' },
    { value: 'ir', text: 'Iran' },
    { value: 'kw', text: 'Koweït' },
    { value: 'kz', text: 'Kazakhstan' },
    { value: 'lu', text: 'Luxembourg' },
    { value: 'nl', text: 'Pays-Bas' },
    { value: 'no', text: 'Norvège' },
    { value: 'nz', text: 'Nouvelle-Zélande' },
    { value: 'pe', text: 'Pérou' },
    { value: 'pl', text: 'Pologne' },
    { value: 'pt', text: 'Portugal' },
    { value: 'qa', text: 'Qatar' },
    { value: 'ro', text: 'Roumanie' },
    { value: 'sa', text: 'Arabie Saoudite' },
    { value: 'se', text: 'Suède' },
    { value: 'sg', text: 'Singapour' },
    { value: 'sk', text: 'Slovaquie' },
    { value: 'th', text: 'Thaïlande' },
    { value: 'tr', text: 'Turquie' },
    { value: 'tw', text: 'Taïwan' },
    { value: 'ua', text: 'Ukraine' },
    { value: 've', text: 'Venezuela' },
    { value: 'vn', text: 'Vietnam' }
];